CREATE TABLE [dbo].[TB_ESTADO] (
    [IDT_ESTADO] INT           IDENTITY (1, 1) NOT NULL,
    [NOM_ESTADO] VARCHAR (255) NOT NULL,
    [SGL_ESTADO] CHAR (2)      NOT NULL,
    CONSTRAINT [PK_ESTADO] PRIMARY KEY CLUSTERED ([IDT_ESTADO] ASC)
);


GO

CREATE TABLE [dbo].[TB_CIDADE] (
    [IDT_CIDADE] INT           IDENTITY (1, 1) NOT NULL,
    [NOM_CIDADE] VARCHAR (255) NOT NULL,
    [IDT_ESTADO] INT           NOT NULL,
    CONSTRAINT [PK_CIDADE] PRIMARY KEY CLUSTERED ([IDT_CIDADE] ASC),
    FOREIGN KEY ([IDT_ESTADO]) REFERENCES [dbo].[TB_ESTADO] ([IDT_ESTADO])
);


GO


CREATE TABLE [dbo].[TB_ENDERECO] (
    IDT_ENDERECO    INT             IDENTITY(1,1) NOT NULL, 
    IDT_USUARIO     INT             NOT NULL , 
    NOM_RUA         varchar(255)    NOT NULL,  
    IDT_CIDADE INT           NOT NULL,
    CONSTRAINT PK_ENDERECO PRIMARY KEY CLUSTERED (IDT_ENDERECO ASC), 
    FOREIGN KEY (IDT_CIDADE) REFERENCES TB_CIDADE(IDT_CIDADE)
    )