USE DB_ATHENA;
/*
CREATE TABLE TB_VILAO (
    IDT_VILAO INT NOT NULL IDENTITY(1,1), 
    NOM_VILAO varchar(255) NOT NULL
    )
    */
CREATE TABLE TB_ESTADO (
    IDT_ESTADO INT NOT NULL IDENTITY(1,1), 
    NOM_ESTADO varchar(255) NOT NULL, 
    SGL_ESTADO char(2) NOT NULL,
    CONSTRAINT PK_ESTADO PRIMARY KEY (IDT_ESTADO)
    )    
CREATE TABLE TB_CIDADE (
    IDT_CIDADE INT NOT NULL IDENTITY(1,1),  
    NOM_CIDADE varchar(255) NOT NULL, 
    IDT_ESTADO INT NOT NULL FOREIGN KEY REFERENCES TB_ESTADO(IDT_ESTADO),    
    CONSTRAINT PK_CIDADE PRIMARY KEY (IDT_CIDADE)
    )
CREATE TABLE TB_ENDERECO (
    IDT_ENDERECO INT NOT NULL IDENTITY(1,1), 
    IDT_USUARIO INT NOT NULL , 
    NOM_RUA varchar(255) NOT NULL, 
    IDT_CIDADE INT NOT NULL FOREIGN KEY REFERENCES TB_CIDADE(IDT_CIDADE),  
    CONSTRAINT PK_ENDERECO PRIMARY KEY (IDT_ENDERECO)
    )
CREATE TABLE TB_USUARIO (
    IDT_USUARIO INT NOT NULL IDENTITY(1,1), 
    NOM_USUARIO varchar(255) NOT NULL
    )
    /*
CREATE TABLE TB_IDENTIDADE (
    IDT_IDENTIDADE INT NOT NULL IDENTITY(1,1), 
    NOM_IDENTIDADE varchar(255) NOT NULL
    )
--USUARIO
INSERT INTO TB_USUARIO (NOM_USUARIO) VALUES ('Batman');
INSERT INTO TB_USUARIO (NOM_USUARIO) VALUES ('Robin');
INSERT INTO TB_USUARIO (NOM_USUARIO) VALUES ('Superman');
INSERT INTO TB_USUARIO (NOM_USUARIO) VALUES ('Wolverine');
INSERT INTO TB_USUARIO (NOM_USUARIO) VALUES ('Deadpool');
--VILAO
INSERT INTO TB_VILAO (NOM_VILAO) VALUES ('Magneto');
INSERT INTO TB_VILAO (NOM_VILAO) VALUES ('Dente de Sabre');
INSERT INTO TB_VILAO (NOM_VILAO) VALUES ('Juggernaut');
INSERT INTO TB_VILAO (NOM_VILAO) VALUES ('Doutor Sinistro');
INSERT INTO TB_VILAO (NOM_VILAO) VALUES ('Mandarim');
INSERT INTO TB_VILAO (NOM_VILAO) VALUES ('Darth Vader');
INSERT INTO TB_VILAO (NOM_VILAO) VALUES ('Lex Luthor');
INSERT INTO TB_VILAO (NOM_VILAO) VALUES ('Joker');
INSERT INTO TB_VILAO (NOM_VILAO) VALUES ('Espantalho');
INSERT INTO TB_VILAO (NOM_VILAO) VALUES ('Morbius');
INSERT INTO TB_VILAO (NOM_VILAO) VALUES ('Kraven');
INSERT INTO TB_VILAO (NOM_VILAO) VALUES ('Doutor Octopus');
*/
--ESTADO*/
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Acre','AC');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Alagoas','AL');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Amapá','AP');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Amazonas','AM');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Bahia','BA');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Ceará','CE');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Distrito Federal','DF');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Espírito Santo','ES');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Goiás','GO');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Maranhão','MA');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Mato Grosso','MT');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Mato Grosso do Sul','MS');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Minas Gerais','MG');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Pará','PA');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Paraíba','PB');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Paraná','PR');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Pernambuco','PE');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Piauí','PI');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Rio de Janeiro','RJ');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Rio Grande do Norte','RN');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Rio Grande do Sul','RS');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Rondônia','RO');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Roraima','RR');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Santa Catarina','SC');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('São Paulo','SP');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Sergipe','SE');
INSERT INTO TB_ESTADO (NOM_ESTADO, SGL_ESTADO) VALUES('Tocantins','TO');